### ISSUE TITLE
Doesn't work for me :(

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [bryik/aframe-ball-throw#9]

**Comment by bryik** [comment]
Heh, it's pretty old at this point. Might need to be updated to the latest version of A-Frame.

What browser and headset are you using? 

Also what isn't working?

**Comment by TheRealDigitalMaster** [comment]
I am playing in browser, not headset (i dont have a phone), so does it only work with the headset, or is it the browser?

**Comment by bryik** [comment]
In theory it should work for VR headsets with motion controllers (HTC Vive, Oculus Rift). Without controllers, you could probably see the boxes but be unable to throw the ball at them.

Without a headset this demo won't work at all.

**Comment by TheRealDigitalMaster** [comment]
Ok :)
